train_transforms:
  RandomResizedCrop:
    interpolation: 'bicubic'
  RandomHorizontalFlip: {}
  ColorJitter:
    brightness: 0.4
    contrast:   0.4
    saturation: 0.4
    hue:        0.2
  GaussianBlur:
    kernel_size: 5
  RandomGrayscale:
    p: 0.2