root: /mnt/local-data/workspace/datasets/
datasets:
  - name: office-31
    dir: office-31/
    num_classes: 31
    domains:
      - domain_name: amazon
        domain_id: 0
        domain_abbr: A
        domain_dir: amazon/
      - domain_name: dslr
        domain_id: 1
        domain_abbr: D
        domain_dir: dslr/
      - domain_name: webcam
        domain_id: 2
        domain_abbr: W
        domain_dir: webcam/

  - name: domainnet
    dir: domainnet/
    num_classes: 345
    domains:
      - domain_name: clipart
        domain_id: 0
        domain_abbr: clp
        domain_dir: clipart/
      - domain_name: infograph
        domain_id: 1
        domain_abbr: inf
        domain_dir: infograph/
      - domain_name: painting
        domain_id: 2
        domain_abbr: pnt
        domain_dir: painting/
      - domain_name: quickdraw
        domain_id: 3
        domain_abbr: qdr
        domain_dir: quickdraw/
      - domain_name: real
        domain_id: 4
        domain_abbr: rel
        domain_dir: real/
      - domain_name: sketch
        domain_id: 5
        domain_abbr: skt
        domain_dir: sketch/

  - name: office-home
    dir: office-home/
    num_classes: 65
    domains:
      - domain_name: Art
        domain_id: 0
        domain_abbr: Ar
        domain_dir: Art/
      - domain_name: Clipart
        domain_id: 1
        domain_abbr: Cl
        domain_dir: Clipart/
      - domain_name: Product
        domain_id: 2
        domain_abbr: Pr
        domain_dir: Product/
      - domain_name: "Real World"
        domain_id: 3
        domain_abbr: Rw
        domain_dir: "Real World/"

  - name: visda-2017
    dir: visda-2017/
    num_classes: 12
    domains:
      - domain_name: synthetic
        domain_id: 0
        domain_abbr: syn
        domain_dir: train/
      - domain_name: real
        domain_id: 1
        domain_abbr: rel
        domain_dir: validation/
